### ISSUE TITLE
Exception when run the default floodlight

### ISSUE THREAD

**Issue by medic0803** [medic0803/Ginkgo-RnD-Project-Floodlight#1]
![image](https://user-images.githubusercontent.com/43716416/103132362-3a052880-46df-11eb-9fb0-14ee2ce7c30d.png)

**Comment by medic0803** [comment]
Failed to create database '/var/lib/floodlight/SyncDB'

**Comment by michael-kang-1** [comment]
解决方法：在本地var/lib 中创建一个floodlight文件夹, 然后
chmod -R 777 floodlight
chown -R root ./foodlight

**Comment by medic0803** [comment]
It works, thx man
