### ISSUE TITLE
MatchUtils.java 报错

### ISSUE THREAD

**Issue by michael-kang-1** [medic0803/Ginkgo-RnD-Project-Floodlight#2]
![image](https://user-images.githubusercontent.com/56579125/103198566-95275d00-4923-11eb-928e-0966cde112b3.png)
mb.setMasked(mf, m.getMasked(mf));

**Comment by medic0803** [comment]
报什么错？

**Comment by michael-kang-1** [comment]
https://github.com/floodlight/floodlight/issues/487#issue-54884147

**Comment by michael-kang-1** [comment]
在eclipse中使用javaSE 1.7, 似乎开发者没有在1.8中测试过

**Comment by michael-kang-1** [comment]
https://github.com/floodlight/floodlight/issues/487#issuecomment-70661408
