### ISSUE TITLE
Idea import steps

### ISSUE THREAD

**Issue by michael-kang-1** [medic0803/Ginkgo-RnD-Project-Floodlight#4]
在git clone 之后，idea并不能直接开始编程，没有src等文件夹

**Comment by michael-kang-1** [comment]
idea执行maven install，idea下载依赖jar包。完成下载后，显示Test包报错，这里忽略不计，主要的Main包文件出现，Floodlight可以启动。
maven install 下载包在本地电脑.m2 文件夹下的repository文件夹下。

**Comment by michael-kang-1** [comment]
ZZY 用以上方法任出现问题

**Comment by K-Ir** [comment]
可以尝试在 _remote.repositories文件中将public=改为central=，或把对应jar包目录中 .lastUpdated结尾的文件删除，虽然在这个问题里没用

**Comment by K-Ir** [comment]
删除maven本地仓库中该jar包对应文件夹下_remote.repositories文件后重新clone，已解决
