### ISSUE TITLE
Unexpected static cache strategy value

### ISSUE THREAD

**Issue by medic0803** [medic0803/Ginkgo-RnD-Project-Floodlight#9]
**Describe the bug**
Get the unexpected static cache strategy value, it seems floodlight modify the value we POST from the web which transfer the IP address with mask to Network address(.0) with mask.

**Screenshots**
<img width="825" alt="image" src="https://user-images.githubusercontent.com/43716416/115982110-1be70080-a5cb-11eb-850a-f3827ca5dfdc.png">

**Comment by kwm01** [comment]
change the IPaddressWithMask to IPaddress. It should be all right for input. Still the web bage function is limited

**Comment by medic0803** [comment]
@kwm01 What you mean about "change the IPaddressWithMask to IPaddress" ? I think we need to input the address with mask on the website due to the identification of different networks based on the mask.
